# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bento < Formula
  desc "TBD
"
  homepage "https://github.com/Cian911/bento"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Cian911/bento/releases/download/v0.0.1/bento_0.0.1_Darwin_x86_64.tar.gz"
      sha256 "3da8acd117a577f09386aadcfa9cb2501a7b687af431295465980b370dc6fc9b"

      def install
        bin.install "bento"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Cian911/bento/releases/download/v0.0.1/bento_0.0.1_Darwin_arm64.tar.gz"
      sha256 "17d41041a798c68ec6fd676720339f41b803c3856d86e200ce07c35977984006"

      def install
        bin.install "bento"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Cian911/bento/releases/download/v0.0.1/bento_0.0.1_Linux_arm64.tar.gz"
      sha256 "36410f79fee7117bad4b8cd17fb0d6930b812e4f8a5d39d9d5cdcac4fe829231"

      def install
        bin.install "bento"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Cian911/bento/releases/download/v0.0.1/bento_0.0.1_Linux_x86_64.tar.gz"
      sha256 "0e6e6f76c58e77c2547e315eae6929d9d6709d0e66362b0116d625fa914fee02"

      def install
        bin.install "bento"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Cian911/bento/releases/download/v0.0.1/bento_0.0.1_Linux_armv6.tar.gz"
      sha256 "ad8799564b7708492f64c6593f9aa7ae9a254dda8848472740019165b6e44dc6"

      def install
        bin.install "bento"
      end
    end
  end
end
