# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bento < Formula
  desc "TBD
"
  homepage "https://github.com/Cian911/bento"
  version "0.0.1-rc"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Cian911/bento/releases/download/v0.0.1-rc/bento_0.0.1-rc_Darwin_arm64.tar.gz"
      sha256 "cd6a7f93a008d85ac1a8000995e3f8214017a4981fc019193d7a329f1245a3d6"

      def install
        bin.install "bento"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Cian911/bento/releases/download/v0.0.1-rc/bento_0.0.1-rc_Darwin_x86_64.tar.gz"
      sha256 "84c4d36807c83711fcfaaca91f12b46e7071207b4c421e6653a9d1c03e581748"

      def install
        bin.install "bento"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Cian911/bento/releases/download/v0.0.1-rc/bento_0.0.1-rc_Linux_arm64.tar.gz"
      sha256 "1443a7b3df34c9a70240b04bac906ae44596930cadc9c30c3440cd0b25a39d57"

      def install
        bin.install "bento"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Cian911/bento/releases/download/v0.0.1-rc/bento_0.0.1-rc_Linux_x86_64.tar.gz"
      sha256 "13c5829708bf3ac8c4af2b8e4a0e6aba2a7b665a63df8d3d20b3d2f9d0d9c9be"

      def install
        bin.install "bento"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Cian911/bento/releases/download/v0.0.1-rc/bento_0.0.1-rc_Linux_armv6.tar.gz"
      sha256 "62abb3ee45be811af84c829019ba34593a2aaa9c9e7e007b7b41a9235ce91428"

      def install
        bin.install "bento"
      end
    end
  end
end
